module.export = {
    TOTAL_ADVERTS: 17108,
    TOTAL_BATCHES: 855,
    BATCHES_SIZE: 20,
    STARTING_BATCH: 0,
    TOTAL_PROCESSED_ADVERTS: 0,
    BATCHES_PER_FULL_RUN: 5,
    FEW_ADVERTS_CUTOFF: 5,
    BATCH_FIRST_DAY: 1
}